/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JeopardyRouteImport } from './routes/jeopardy'
import { Route as IndexRouteImport } from './routes/index'

const JeopardyRoute = JeopardyRouteImport.update({
  id: '/jeopardy',
  path: '/jeopardy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jeopardy': typeof JeopardyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jeopardy': typeof JeopardyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jeopardy': typeof JeopardyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jeopardy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jeopardy'
  id: '__root__' | '/' | '/jeopardy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JeopardyRoute: typeof JeopardyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jeopardy': {
      id: '/jeopardy'
      path: '/jeopardy'
      fullPath: '/jeopardy'
      preLoaderRoute: typeof JeopardyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JeopardyRoute: JeopardyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
